gantt
  title Simple Project
  dateFormat YYYY-MM-DD
  axisFormat %d/%m
  
  section Phase 1
  Task 1    :done, t1, 2025-08-11, 1d
  Task 2    :active, t2, 2025-08-12, 1d
  
  section Phase 2  
  Task 3    :t3, 2025-08-13, 1d