gantt
  title ETL Debrito Test
  dateFormat YYYY-MM-DD
  axisFormat %d/%m
  
  section Test
  Epic 0: Environment Setup    :done, e0, 2025-08-11, 1d
  Epic 1: Core Development      :active, e1, 2025-08-12, 2d